name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install ruff
        run: pip install ruff
      - name: Ruff check
        run: ruff check .
      - name: Ruff format (check only)
        run: ruff format --check .

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: ecommerce_db
          POSTGRES_USER: ecommerce_user
          POSTGRES_PASSWORD: supersecret
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U ecommerce_user -d ecommerce_db"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt

      - name: Set env (DB/Redis)
        run: |
          echo "DATABASE_URL=postgresql+psycopg://ecommerce_user:supersecret@localhost:5432/ecommerce_db" >> $GITHUB_ENV
          echo "REDIS_URL=redis://localhost:6379/0" >> $GITHUB_ENV

      - name: Apply migrations
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: alembic upgrade head

      - name: Run tests
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: pytest -q
